[package]
name = "app_locker"
version.workspace = true
edition.workspace = true

[dependencies]
app_core = { path = "../core" }
infra = { path = "../infra" }
slint = { version = "1.15.1", default-features = false, features = ["backend-winit", "renderer-software", "compat-1-2"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rfd = "0.17.2"
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time", "process", "net", "io-util"] }
tracing.workspace = true
tracing-subscriber = "0.3"
anyhow.workspace = true
windows-service.workspace = true

[build-dependencies]
slint-build = "1.15.1"

[dependencies.windows]
version = "0.52"
features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Services",
]
